server:
  port: 8888

spring:
  application:
    name: config-server
  config:
    import: application-secrets.yml
  cloud:
    config:
      server:
        git:
          search-paths:
            - '{profile}'